### ISSUE TITLE
unbound local error gpt_sovits.py

### ISSUE THREAD

**Issue by nekohacker591** [0Xiaohei0/LocalAIVtuber#22]
INFO:     Number of parameter: 77.49M
init finished, time elapsed: 405.44063997268677
replacing decimal point with the word point.
original:) すぅ…はぁ——おはようさん、朝の空気は清々しくて気持ちええなぁ、深呼吸して頭もすっきりや。
replaced_text: すぅ…はぁ——おはようさん、朝の空気は清々しくて気持ちええなぁ、深呼吸して頭もすっきりや。
tts start
torch.cuda.is_available() True
refer_wav_path C:\Users\michael\Downloads\New folder (11)\LAV_v0.2\plugins\gpt_sovits\models\nene\The sun is shining brightly in the clear blue sky..wav
prompt_text The sun is shining brightly in the clear blue sky.
prompt_language en
Failed to generate audio file.
**********************************************************************
  Resource averaged_perceptron_tagger_eng not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('averaged_perceptron_tagger_eng')

  For more information see: https://www.nltk.org/data.html

  Attempted to load taggers/averaged_perceptron_tagger_eng/

  Searched in:
    - 'C:\\Users\\michael/nltk_data'
    - 'C:\\Users\\michael\\Downloads\\New folder (11)\\LAV_v0.2\\venv\\nltk_data'
    - 'C:\\Users\\michael\\Downloads\\New folder (11)\\LAV_v0.2\\venv\\share\\nltk_data'
    - 'C:\\Users\\michael\\Downloads\\New folder (11)\\LAV_v0.2\\venv\\lib\\nltk_data'
    - 'C:\\Users\\michael\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************

Traceback (most recent call last):
  File "C:\Users\michael\Downloads\New folder (11)\LAV_v0.2\venv\Lib\site-packages\gradio\queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\michael\Downloads\New folder (11)\LAV_v0.2\venv\Lib\site-packages\gradio\route_utils.py", line 270, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\michael\Downloads\New folder (11)\LAV_v0.2\venv\Lib\site-packages\gradio\blocks.py", line 1847, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\michael\Downloads\New folder (11)\LAV_v0.2\venv\Lib\site-packages\gradio\blocks.py", line 1433, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\michael\Downloads\New folder (11)\LAV_v0.2\venv\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\michael\Downloads\New folder (11)\LAV_v0.2\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\michael\Downloads\New folder (11)\LAV_v0.2\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\michael\Downloads\New folder (11)\LAV_v0.2\venv\Lib\site-packages\gradio\utils.py", line 805, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\michael\Downloads\New folder (11)\LAV_v0.2\TTS.py", line 70, in wrapper_synthesize
    result = self.current_plugin.synthesize(text)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\michael\Downloads\New folder (11)\LAV_v0.2\plugins\gpt_sovits\gptSovits.py", line 63, in synthesize
    return response
           ^^^^^^^^
UnboundLocalError: cannot access local variable 'response' where it is not associated with a value

![image](https://github.com/user-attachments/assets/219841f7-c204-4b99-8710-2e21c7969b5a)

**Comment by 0Xiaohei0** [comment]
You need to:
pip install nltk
python -m nltk.downloader -d C:\nltk_data all
