### ISSUE TITLE
Installation issue, on getting requirements to build wheel after installing numba

### ISSUE THREAD

**Issue by pythontor** [0Xiaohei0/LocalAIVtuber#23]
Good evening everyone, I've got a problem during installation of requirements for this project. Once I get to numba on the point when the system tries to get requirements to build wheel it returns with an error, stopping the installation. Here's what I get. I may be blind that I don't see the issue in this code, or I'm plain stupid and don't know how to fix it. Please do help.

Collecting numba==0.58.1 (from -r requirements.txt (line 91))
  Using cached numba-0.58.1.tar.gz (2.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "C:\AIVtube\LAV_v0.2\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\AIVtube\LAV_v0.2\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\AIVtube\LAV_v0.2\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\максим\AppData\Local\Temp\pip-build-env-4ipqkf64\overlay\Lib\site-packages\setuptools\build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\максим\AppData\Local\Temp\pip-build-env-4ipqkf64\overlay\Lib\site-packages\setuptools\build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "C:\Users\максим\AppData\Local\Temp\pip-build-env-4ipqkf64\overlay\Lib\site-packages\setuptools\build_meta.py", line 503, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\максим\AppData\Local\Temp\pip-build-env-4ipqkf64\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 51, in <module>
        File "<string>", line 48, in _guard_py_ver
      RuntimeError: Cannot install on Python version 3.12.0; only versions >=3.8,<3.12 are supported.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip

**Comment by pythontor** [comment]
I have removed my python 3.12 from laptop. Maybe this will work.

**Comment by pythontor** [comment]
That did not help, it still tries to be installed by python 3.12

**Comment by pythontor** [comment]
The issue is fixed.
