### ISSUE TITLE
Error while loading main.py

### ISSUE THREAD

**Issue by vcoopers** [0Xiaohei0/LocalAIVtuber#26]
Hi, wondering if you can help...I.m facing an issue when loading the main.py

Traceback (most recent call last):
  File "C:\CP\LocalAIVtuber\venv\lib\site-packages\transformers\utils\hub.py", line 403, in cached_file
    resolved_file = hf_hub_download(
  File "C:\CP\LocalAIVtuber\venv\lib\site-packages\huggingface_hub\utils\_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "C:\CP\LocalAIVtuber\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "C:\CP\LocalAIVtuber\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 154, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'C:\CP\LocalAIVtuber\plugins\gpt_sovits\GPT_SoVITS\./pretrained_models/chinese-roberta-wwm-ext-large'. Use `repo_type` argument if needed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\CP\LocalAIVtuber\main.py", line 30, in <module>
    tts = TTS()
  File "C:\CP\LocalAIVtuber\TTS.py", line 39, in __init__
    super().__init__(TTSPluginInterface)
  File "C:\CP\LocalAIVtuber\pluginSelectionBase.py", line 36, in __init__
    self.load_provider(provider.name)
  File "C:\CP\LocalAIVtuber\pluginSelectionBase.py", line 67, in load_provider
    found_provider.plugin.init()
  File "C:\CP\LocalAIVtuber\plugins\gpt_sovits\gptSovits.py", line 50, in init
    self.load_voice_config()
  File "C:\CP\LocalAIVtuber\plugins\gpt_sovits\gptSovits.py", line 47, in load_voice_config
    api.init(sovits_path, gpt_path, reference_audio_path, reference_audio_text, reference_audio_language)
  File "C:\CP\LocalAIVtuber\plugins\gpt_sovits\GPT_SoVITS\api_direct.py", line 142, in init
    tokenizer = AutoTokenizer.from_pretrained(bert_path)
  File "C:\CP\LocalAIVtuber\venv\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 844, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "C:\CP\LocalAIVtuber\venv\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 676, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "C:\CP\LocalAIVtuber\venv\lib\site-packages\transformers\utils\hub.py", line 469, in cached_file
    raise EnvironmentError(
OSError: Incorrect path_or_model_id: 'C:\CP\LocalAIVtuber\plugins\gpt_sovits\GPT_SoVITS\./pretrained_models/chinese-roberta-wwm-ext-large'. Please provide either the path to a local folder or the repo_id of a model on the Hub.

**Comment by 0Xiaohei0** [comment]
Looks like the model files are missing, if you cloned the repo, you can find the model files in the zip file in releases. Replace the plugins/gptsovits folder with the one from the zip file.

**Comment by oivio** [comment]
@0Xiaohei0 
I did come a cross similar issue but I did made installation from zip file that is provided in releases.
When I try to run` python main.py`  I do get error :

```
E:\LAV_v0.2>python main.py
Traceback (most recent call last):
  File "E:\LAV_v0.2\main.py", line 7, in <module>
    from TTS import TTS
  File "E:\LAV_v0.2\TTS.py", line 17, in <module>
    import simpleaudio as sa
ModuleNotFoundError: No module named 'simpleaudio'
```

**Comment by 0Xiaohei0** [comment]
The installation step did not run correctly, you need to send any errors during pip install -r requirements.txt

**Comment by oivio** [comment]
thank you @0Xiaohei0  I did run req and did get that:

rror: invalid-installed-package

```
× Cannot process installed package omegaconf 2.0.6 in 'd:\\\lav_v0.2\\venv\\lib\\site-packages' because it has an invalid requirement:
│ .* suffix can only be used with `==` or `!=` operators
│     PyYAML (>=5.1.*)
│             ~~~~~~^
╰─> Starting with pip 24.1, packages with invalid requirements can not be processed.

hint: To proceed this package must be uninstalled.
```
