### ISSUE TITLE
RVC error? maybe its just me?

### ISSUE THREAD

**Issue by Zimigames** [0Xiaohei0/LocalAIVtuber#27]
When choosing RVC as Provider i get error: 

Traceback (most recent call last):
  File "E:\LocalAIVtuber-master\venv\lib\site-packages\gradio\queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
  File "E:\LocalAIVtuber-master\venv\lib\site-packages\gradio\route_utils.py", line 270, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\LocalAIVtuber-master\venv\lib\site-packages\gradio\blocks.py", line 1847, in process_api
    result = await self.call_function(
  File "E:\LocalAIVtuber-master\venv\lib\site-packages\gradio\blocks.py", line 1433, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\LocalAIVtuber-master\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "E:\LocalAIVtuber-master\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "E:\LocalAIVtuber-master\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "E:\LocalAIVtuber-master\venv\lib\site-packages\gradio\utils.py", line 805, in wrapper
    response = f(*args, **kwargs)
  File "E:\LocalAIVtuber-master\TTS.py", line 70, in wrapper_synthesize
    result = self.current_plugin.synthesize(text)
  File "E:\LocalAIVtuber-master\plugins\rvc\rvc_plugin.py", line 80, in synthesize
    paudio1 = self.model(aud, f0_up_key=self.transpose,
  File "E:\LocalAIVtuber-master\plugins\rvc\inferrvc\modules.py", line 313, in __call__
    return self.run(audio, f0_up_key, f0_method, index_rate, filter_radius, protect, output_device, output_volume, f0_spec)
  File "E:\LocalAIVtuber-master\plugins\rvc\inferrvc\modules.py", line 375, in run
    audio_opt = self.pipeline.pipeline(
  File "E:\LocalAIVtuber-master\plugins\rvc\inferrvc\pipeline.py", line 397, in pipeline
    self.vc(
  File "E:\LocalAIVtuber-master\plugins\rvc\inferrvc\pipeline.py", line 202, in vc
    logits = model.extract_features(**inputs)
  File "E:\LocalAIVtuber-master\venv\lib\site-packages\fairseq\models\hubert\hubert.py", line 535, in extract_features
    res = self.forward(
  File "E:\LocalAIVtuber-master\venv\lib\site-packages\fairseq\models\hubert\hubert.py", line 467, in forward
    x, _ = self.encoder(
  File "E:\LocalAIVtuber-master\venv\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\LocalAIVtuber-master\venv\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\LocalAIVtuber-master\venv\lib\site-packages\fairseq\models\wav2vec\wav2vec2.py", line 1003, in forward
    x, layer_results = self.extract_features(x, padding_mask, layer)
  File "E:\LocalAIVtuber-master\venv\lib\site-packages\fairseq\models\wav2vec\wav2vec2.py", line 1049, in extract_features
    x, (z, lr) = layer(
  File "E:\LocalAIVtuber-master\venv\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\LocalAIVtuber-master\venv\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\LocalAIVtuber-master\venv\lib\site-packages\fairseq\models\wav2vec\wav2vec2.py", line 1260, in forward
    x, attn = self.self_attn(
  File "E:\LocalAIVtuber-master\venv\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\LocalAIVtuber-master\venv\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\LocalAIVtuber-master\venv\lib\site-packages\fairseq\modules\multihead_attention.py", line 538, in forward
    return F.multi_head_attention_forward(
  File "E:\LocalAIVtuber-master\plugins\gpt_sovits\GPT_SoVITS\AR\modules\patched_mha_with_cache.py", line 257, in multi_head_attention_forward_patched
    q, k, v = _in_projection(
NameError: name '_in_projection' is not defined

**Comment by 0Xiaohei0** [comment]
You cannot enable gpt sovits and rvc at the same time, some of their modules have conflict
